#include<stdio.h>
#include<stdlib.h>
#include "header.h"
#include<string.h>

int generate_input_file(struct _start * head, struct _start_follow *head_follow, struct _p_end * head_terminal, struct _table_head * head_parser_table)
{
char command[100], filename[100],input[100],output[100],inout_file[100];
FILE *input_file,*output_file;

//printf("\n HEllo i m here");
/* execute the lex file to get the c source file */
strcpy(command,"flex -l ");
strcat(command,"lex_file.l");

/* run the lex file to generate the intermediate source code for lex in c */
system(command);

/* create the executive file 'lex_file' by compiling intermediate source code in c named lex.yy.c */
strcpy(command,"gcc lex.yy.c -o lex_file");
system(command);

//system("clear");

/* enter input stream to be processed */

printf("\nEnter The Input To Be Parsed...");
fgets(input,100,stdin);
input[strlen(input)-1] = '\0';
fputs("\n\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",log_fp);
fprintf(log_fp,"\n%s%s","Given Input To Be Parsed...",input);
/* concatenate the end of file symbol "#" at the end of input */
strcat(input,"#");

/* write the input to a the file "input.in" to feed the executable the lex code */
input_file = fopen("input.in","w");
//check_file(input_file);
fprintf(input_file,"%s",input);
fclose(input_file);

/* execute the file generated by after compiling the c source which is generated by lex */
strcpy(command,"./lex_file");
strcat(command," input.in");
system(command);

/* read the token string from the output file generated by lex */
input_file = fopen("input.out","r");
//check_file(input_file);
fgets(input,200,input_file);
input[strlen(input)-1] = '\0';
fclose(input_file);

/* process the input token string converted by lex */
//process_input(fp_log,parser_table,input,terminals,non_terminals,grammar->lhs,num_term,num_nonterm);

//printf("Wan't To Continue...(y/n): ");
//scanf("%c",&wish);

/* newline is in stdin and so clear the input buffer before any further scans in the beginning of the loop */
//while (getchar() != '\n') 
//continue;

printf("\n");

return(0);
}

